"""reconcile_schema_with_models

Revision ID: f731f38ddb3d
Revises: c3f7a1b2d4e5
Create Date: 2026-08-31 18:32:17.390503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f731f38ddb3d'
down_revision: Union[str, Sequence[str], None] = 'c3f7a1b2d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('hash_algorithm', sa.String(length=16), nullable=True))
    op.add_column('documents', sa.Column('hashed_at', sa.DateTime(), nullable=True))
    op.add_column('regulation_fields', sa.Column('legal_basis', sa.String(), nullable=True))
    op.add_column('regulation_fields', sa.Column('penalty_tier', sa.String(), nullable=True))
    op.add_column('regulation_fields', sa.Column('enforcement_body', sa.String(), nullable=True))
    op.add_column('regulation_fields', sa.Column('cross_references', sa.JSON(), nullable=True))
    op.add_column('reporting_projects', sa.Column('reporting_year', sa.Integer(), nullable=True))
    op.add_column('reporting_projects', sa.Column('industry_sector', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_users_organization_id', 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.add_column('validation_results', sa.Column('regulation_ref', sa.String(), nullable=True))
    op.add_column('validation_results', sa.Column('legal_consequence', sa.Text(), nullable=True))
    op.add_column('validation_results', sa.Column('penalty_range', sa.String(), nullable=True))
    op.add_column('validation_results', sa.Column('remediation', sa.Text(), nullable=True))
    op.add_column('validation_results', sa.Column('escalation_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_results', 'escalation_required')
    op.drop_column('validation_results', 'remediation')
    op.drop_column('validation_results', 'penalty_range')
    op.drop_column('validation_results', 'legal_consequence')
    op.drop_column('validation_results', 'regulation_ref')
    op.drop_constraint('fk_users_organization_id', 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_column('reporting_projects', 'industry_sector')
    op.drop_column('reporting_projects', 'reporting_year')
    op.drop_column('regulation_fields', 'cross_references')
    op.drop_column('regulation_fields', 'enforcement_body')
    op.drop_column('regulation_fields', 'penalty_tier')
    op.drop_column('regulation_fields', 'legal_basis')
    op.drop_column('documents', 'hashed_at')
    op.drop_column('documents', 'hash_algorithm')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
