import logging
from app.database import SessionLocal
from app.models import RegulationField, Organization, Product, User, UserRole
from app.auth import get_password_hash

logger = logging.getLogger(__name__)

# =============================================================================
# SFDR Fields — fully enriched with legal consequence metadata
# =============================================================================
SFDR_FIELDS = [
    # --- Entity-Level PAI (Principal Adverse Impacts) ---
    {
        "id": "field_pai_ghg_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_GHG_SCOPE1",
        "field_label": "Scope 1 GHG Emissions",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 1",
        "penalty_tier": "Critical",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "EU Taxonomy", "field_code": "TAX_CLIMATE_MIT", "relationship": "data_dependency"}
        ],
        "guidance": {
            "description": "Scope 1 greenhouse gas emissions generated by investee companies.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_ghg_2",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_GHG_SCOPE2",
        "field_label": "Scope 2 GHG Emissions",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 2",
        "penalty_tier": "Critical",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Scope 2 greenhouse gas emissions generated by investee companies.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_ghg_3",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_GHG_SCOPE3",
        "field_label": "Scope 3 GHG Emissions",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 3",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "supplementary_data"}
        ],
        "guidance": {
            "description": "Scope 3 greenhouse gas emissions generated by investee companies.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_carb_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_CARBON_FOOTPRINT",
        "field_label": "Carbon Footprint",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 4",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "derived_metric"}
        ],
        "guidance": {
            "description": "Carbon footprint of the investment portfolio.",
            "unit": "tCO2e/EURm",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_ff_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_FOSSIL_FUEL",
        "field_label": "Exposure to Fossil Fuel Companies",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 5",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "EU Taxonomy", "field_code": "TAX_FOSSIL_EXCL", "relationship": "exclusion_alignment"}
        ],
        "guidance": {
            "description": "Share of investments in investee companies active in the fossil fuel sector.",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_pai_wat_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_WATER_EMISSIONS",
        "field_label": "Emissions to Water",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 8",
        "penalty_tier": "Medium",
        "enforcement_body": "National Competent Authority",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_WATER_USE", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Tonnes of emissions to water generated by investee companies per million EUR invested, expressed as a weighted average.",
            "unit": "tonnes/EURm",
            "rule_checks": ["numeric_only", "must_have_evidence"]
        }
    },
    {
        "id": "field_pai_div_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_BOARD_GENDER_DIVERSITY",
        "field_label": "Board Gender Diversity",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 13",
        "penalty_tier": "Medium",
        "enforcement_body": "National Competent Authority",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GENDER_PAY_GAP", "relationship": "complementary_indicator"},
            {"framework": "CSRD", "field_code": "CSRD_GOVERNANCE_BOARD", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Average ratio of female to male board members in investee companies.",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    
    # --- Periodic Report Annexes (Article 8 / Article 9) ---
    {
        "id": "field_per_sustain_target",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_SUSTAIN_INVEST_TARGET",
        "field_label": "Attainment of Sustainable Investment Objective",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [],
        "guidance": {
            "description": "To what extent was the sustainable investment objective attained during the reporting period?",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_top_invest",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_TOP_INVESTMENTS",
        "field_label": "Top Investments",
        "field_kind": "table",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV Section 'What were the top investments?'",
        "penalty_tier": "Medium",
        "enforcement_body": "National Competent Authority",
        "cross_references": [],
        "guidance": {
            "description": "List of top 15 investments of the financial product during the reporting period (Sector, Country, % Assets).",
            "rule_checks": ["table_columns", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_asset_alloc",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_ASSET_ALLOCATION",
        "field_label": "Proportion of Sustainability-related Investments",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV Section 'Asset Allocation'",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [],
        "guidance": {
            "description": "What was the proportion of sustainability-related investments during the reporting period?",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_tax_aligned",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_TAXONOMY_ALIGNMENT",
        "field_label": "Taxonomy-aligned Activities",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV; EU Taxonomy Regulation Art. 5-6",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "EU Taxonomy", "field_code": "TAX_ALIGNMENT_PCT", "relationship": "direct_dependency"}
        ],
        "guidance": {
            "description": "To what extent were the sustainable investments aligned with the EU Taxonomy?",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_social_obj",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_SOCIAL_OBJECTIVE",
        "field_label": "Share of Socially Sustainable Investments",
        "field_kind": "numeric",
        "mandatory": False,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV (optional social dimension)",
        "penalty_tier": "Low",
        "enforcement_body": "National Competent Authority",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GENDER_PAY_GAP", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "What was the share of socially sustainable investments?",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range"]
        }
    }
]

# =============================================================================
# CSRD Cross-Framework Fields — representative set under ESRS standards
# =============================================================================
CSRD_FIELDS = [
    {
        "id": "field_csrd_ghg_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",  # shares disclosure_type for cross-mapping
        "annex_code": "ESRS E1",
        "field_code": "CSRD_GHG_SCOPE1",
        "field_label": "GHG Emissions (ESRS E1 — Scope 1, 2, 3)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS E1-6 (Gross GHG emissions)",
        "penalty_tier": "Critical",
        "enforcement_body": "Member State Authority / EFRAG",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE2", "relationship": "equivalent_disclosure"},
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE3", "relationship": "supplementary_data"}
        ],
        "guidance": {
            "description": "Gross Scope 1, 2, and 3 GHG emissions in accordance with ESRS E1-6. Undertakings shall disclose in metric tons of CO2 equivalent.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_csrd_water_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS E3",
        "field_code": "CSRD_WATER_USE",
        "field_label": "Water Consumption (ESRS E3)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS E3-4 (Water consumption)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_WATER_EMISSIONS", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Total water consumption in cubic meters, with breakdown by areas of water stress where applicable.",
            "unit": "m³",
            "rule_checks": ["numeric_only", "must_have_evidence"]
        }
    },
    {
        "id": "field_csrd_gender_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS S1",
        "field_code": "CSRD_GENDER_PAY_GAP",
        "field_label": "Gender Pay Gap (ESRS S1)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS S1-16 (Remuneration metrics, pay gap)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_BOARD_GENDER_DIVERSITY", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "The difference between the average gross hourly earnings of male and female employees as a percentage of male gross earnings.",
            "unit": "%",
            "rule_checks": ["numeric_only", "must_have_evidence"]
        }
    },
    {
        "id": "field_csrd_bio_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS E4",
        "field_code": "CSRD_BIODIVERSITY",
        "field_label": "Biodiversity Impact (ESRS E4)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS E4-5 (Impact metrics on biodiversity)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [],
        "guidance": {
            "description": "Disclosure of significant impacts on biodiversity and ecosystems, including land use change and ecosystem degradation.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_csrd_gov_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS G1",
        "field_code": "CSRD_GOVERNANCE_BOARD",
        "field_label": "Board Composition & Diversity (ESRS G1)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS 2 GOV-1 (Board composition)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_BOARD_GENDER_DIVERSITY", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Composition of administrative, management and supervisory bodies by gender and other diversity indicators.",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_csrd_e1_energy",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS E1",
        "field_code": "CSRD_ENERGY_CONSUMPTION",
        "field_label": "Energy Consumption & Mix (ESRS E1-5)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS E1-5 (Energy consumption and mix)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority / EFRAG",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE1", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Total energy consumption in MWh, split by source and energy mix, embedded in ESRS E1-5.",
            "unit": "MWh",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_csrd_e2_poll",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS E2",
        "field_code": "CSRD_POLLUTION",
        "field_label": "Pollution Impacts (ESRS E2)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS E2 (Pollution)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [],
        "guidance": {
            "description": "Disclosure of emissions to air, water and soil; and substances of concern per ESRS E2.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_csrd_s1_workforce",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS S1",
        "field_code": "CSRD_OWN_WORKFORCE",
        "field_label": "Own Workforce Metrics (ESRS S1)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS S1 (Own workforce)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_BOARD_GENDER_DIVERSITY", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Disclosure of workforce characteristics, health and safety, and own-workforce metrics per ESRS S1.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_csrd_g1_business",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS G1",
        "field_code": "CSRD_BUSINESS_CONDUCT",
        "field_label": "Business Conduct (ESRS G1)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS G1 (Business conduct)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [],
        "guidance": {
            "description": "Disclosure of anti-corruption, anti-bribery, and business-conduct policies per ESRS G1.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    }
]

# =============================================================================
# SEC Climate Disclosure Rule Fields (17 CFR Part 229)
# =============================================================================
SEC_FIELDS = [
    {
        "id": "field_sec_ghg_1",
        "framework": "SEC",
        "disclosure_type": "entity_pai",
        "annex_code": "17 CFR 229.1500",
        "field_code": "SEC_GHG_SCOPE1",
        "field_label": "GHG Scope 1 Emissions (SEC Climate Rule)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "SEC Climate Rule 2024",
        "legal_basis": "SEC Climate Disclosure Rule, 17 CFR 229.1500",
        "penalty_tier": "High",
        "enforcement_body": "US Securities and Exchange Commission (SEC)",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "ISSB", "field_code": "ISSB_S2_GHG", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Direct GHG emissions from sources owned or controlled by the registrant, in metric tons of CO2e.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_sec_ghg_2",
        "framework": "SEC",
        "disclosure_type": "entity_pai",
        "annex_code": "17 CFR 229.1500",
        "field_code": "SEC_GHG_SCOPE2",
        "field_label": "GHG Scope 2 Emissions (SEC Climate Rule)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "SEC Climate Rule 2024",
        "legal_basis": "SEC Climate Disclosure Rule, 17 CFR 229.1500",
        "penalty_tier": "High",
        "enforcement_body": "US Securities and Exchange Commission (SEC)",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE2", "relationship": "equivalent_disclosure"},
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "ISSB", "field_code": "ISSB_S2_GHG", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Indirect emissions from purchased electricity, steam, heating, or cooling consumed by the registrant.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_sec_ghg_3",
        "framework": "SEC",
        "disclosure_type": "entity_pai",
        "annex_code": "17 CFR 229.1500(c)",
        "field_code": "SEC_GHG_SCOPE3",
        "field_label": "GHG Scope 3 Emissions (SEC Climate Rule)",
        "field_kind": "numeric",
        "mandatory": False,
        "regulation_version": "SEC Climate Rule 2024",
        "legal_basis": "SEC Climate Disclosure Rule, 17 CFR 229.1500(c) (Scope 3 disclosure — subject to compliance timing)",
        "penalty_tier": "Medium",
        "enforcement_body": "US Securities and Exchange Commission (SEC)",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE3", "relationship": "equivalent_disclosure"},
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "ISSB", "field_code": "ISSB_S2_GHG", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Indirect emissions in the value chain (upstream and downstream), including supplier and customer activities.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_sec_climate_risk",
        "framework": "SEC",
        "disclosure_type": "entity_pai",
        "annex_code": "17 CFR 229.1502",
        "field_code": "SEC_CLIMATE_RISK",
        "field_label": "Climate-Related Risk Management (SEC Climate Rule)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "SEC Climate Rule 2024",
        "legal_basis": "SEC Climate Disclosure Rule, 17 CFR 229.1502 (Risk Management, Strategy, Governance)",
        "penalty_tier": "High",
        "enforcement_body": "US Securities and Exchange Commission (SEC)",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "complementary_indicator"},
            {"framework": "ISSB", "field_code": "ISSB_S2_TRANSITION", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Disclosure of governance, strategy, and risk management regarding climate-related risks and opportunities.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_sec_fin_impact",
        "framework": "SEC",
        "disclosure_type": "entity_pai",
        "annex_code": "17 CFR 229.1502(d)",
        "field_code": "SEC_FINANCIAL_IMPACT",
        "field_label": "Financial Impact of Climate Events (SEC Climate Rule)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "SEC Climate Rule 2024",
        "legal_basis": "SEC Climate Disclosure Rule, 17 CFR 229.1502(d) (Financial statement effects)",
        "penalty_tier": "High",
        "enforcement_body": "US Securities and Exchange Commission (SEC)",
        "cross_references": [
            {"framework": "ISSB", "field_code": "ISSB_S1_GOODS_SERVICES", "relationship": "equivalent_disclosure"},
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Quantified financial impact of severe weather events, natural conditions, and transition activities.",
            "unit": "USD",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    }
]

# =============================================================================
# UK SDR (FCA PS23/16) Fields
# =============================================================================
UK_SDR_FIELDS = [
    {
        "id": "field_uksdr_label",
        "framework": "UK SDR",
        "disclosure_type": "periodic",
        "annex_code": "FCA PS23/16",
        "field_code": "UKSDR_SUSTAINABILITY_LABEL",
        "field_label": "UK SDR Sustainability Label",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "UK SDR 2024",
        "legal_basis": "FCA PS23/16 Sustainability Disclosure Requirements (SDR)",
        "penalty_tier": "High",
        "enforcement_body": "Financial Conduct Authority (FCA)",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PERIODIC_ASSET_ALLOCATION", "relationship": "equivalent_disclosure"},
            {"framework": "EU Taxonomy", "field_code": "TAX_ALIGNMENT_PCT", "relationship": "supplementary_data"}
        ],
        "guidance": {
            "description": "Designation of fund under UK SDR labels: Sustainability Improver, Sustainability Focus, Sustainability Impact, or Sustainability Mixed Goals.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_uksdr_ghg",
        "framework": "UK SDR",
        "disclosure_type": "entity_pai",
        "annex_code": "FCA PS23/16",
        "field_code": "UKSDR_GHG_EMISSIONS",
        "field_label": "Sustainability Objective — GHG Metric (UK SDR)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "UK SDR 2024",
        "legal_basis": "FCA PS23/16 — product-level sustainability objective and key performance indicators",
        "penalty_tier": "Hard",
        "enforcement_body": "Financial Conduct Authority (FCA)",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE3", "relationship": "equivalent_disclosure"},
            {"framework": "ISSB", "field_code": "ISSB_S2_GHG", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "GHG emissions metric used to demonstrate progress towards the sustainability objective.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_uksdr_improving",
        "framework": "UK SDR",
        "disclosure_type": "periodic",
        "annex_code": "FCA PS23/16",
        "field_code": "UKSDR_ODD_AND_FLAGSHIP",
        "field_label": "Sustainability Improver / Impact Category",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "UK SDR 2024",
        "legal_basis": "FCA PS23/16 — SDR labels and anti-greenwashing rule",
        "penalty_tier": "Medium",
        "enforcement_body": "Financial Conduct Authority (FCA)",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PERIODIC_SUSTAIN_INVEST_TARGET", "relationship": "equivalent_disclosure"},
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Qualification for 'Improver' or 'Impact' SDR categories based on the scheme's sustainability objective.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_uksdr_anti_gw",
        "framework": "UK SDR",
        "disclosure_type": "periodic",
        "annex_code": "FCA COBS 4.3.8",
        "field_code": "UKSDR_ANTI_GREENWASHING",
        "field_label": "Anti-Greenwashing Compliance (FCA COBS 4.3.8)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "UK SDR 2024",
        "legal_basis": "FCA COBS 4.3.8 (Anti-Greenwashing Rule under PS23/16)",
        "penalty_tier": "High",
        "enforcement_body": "Financial Conduct Authority (FCA)",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PERIODIC_ASSET_ALLOCATION", "relationship": "equivalent_disclosure"},
            {"framework": "SFDR", "field_code": "PERIODIC_SUSTAIN_INVEST_TARGET", "relationship": "supplementary_data"}
        ],
        "guidance": {
            "description": "Demonstrate that any sustainability-related claims are fair, clear, and not misleading (FCA anti-greenwashing rule).",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_uksdr_policy",
        "framework": "UK SDR",
        "disclosure_type": "periodic",
        "annex_code": "FCA PS23/16",
        "field_code": "UKSDR_INVESTMENT_POLICY",
        "field_label": "Sustainable Investment Policy (UK SDR)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "UK SDR 2024",
        "legal_basis": "FCA PS23/16 — investment policy and stewardship disclosures for SDR-labelled products",
        "penalty_tier": "Medium",
        "enforcement_body": "Financial Conduct Authority (FCA)",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PERIODIC_SUSTAIN_INVEST_TARGET", "relationship": "equivalent_disclosure"},
            {"framework": "ISSB", "field_code": "ISSB_S2_TARGETS", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Description of the investment policy and how it contributes to the stated sustainability objective.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    }
]

# =============================================================================
# ISSB S1 / S2 Standards Fields
# =============================================================================
ISSB_FIELDS = [
    {
        "id": "field_issb_s2_ghg",
        "framework": "ISSB",
        "disclosure_type": "entity_pai",
        "annex_code": "IFRS S2 B62",
        "field_code": "ISSB_S2_GHG",
        "field_label": "IFRS S2 GHG Emissions (Scope 1, 2, 3)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "IFRS S2 (2023)",
        "legal_basis": "IFRS S2 Climate-related Disclosures, para B62-B67 (GHG emissions)",
        "penalty_tier": "High",
        "enforcement_body": "ISSB / National SDR Jurisdiction",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE2", "relationship": "equivalent_disclosure"},
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE3", "relationship": "equivalent_disclosure"},
            {"framework": "SEC", "field_code": "SEC_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "SEC", "field_code": "SEC_GHG_SCOPE2", "relationship": "equivalent_disclosure"},
            {"framework": "SEC", "field_code": "SEC_GHG_SCOPE3", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Gross GHG emissions across Scope 1, 2, and 3 in accordance with the GHG Protocol.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_issb_s2_transition",
        "framework": "ISSB",
        "disclosure_type": "entity_pai",
        "annex_code": "IFRS S2 B24",
        "field_code": "ISSB_S2_TRANSITION",
        "field_label": "Climate Transition Plan (IFRS S2)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "IFRS S2 (2023)",
        "legal_basis": "IFRS S2 Climate-related Disclosures, para B24-B28 (transition plans)",
        "penalty_tier": "Medium",
        "enforcement_body": "ISSB / National SDR Jurisdiction",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "SEC", "field_code": "SEC_CLIMATE_RISK", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Disclosure of transition plans aligned to the global temperature goals, including milestones and financing.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_issb_s1_finance",
        "framework": "ISSB",
        "disclosure_type": "entity_pai",
        "annex_code": "IFRS S1",
        "field_code": "ISSB_S1_GOODS_SERVICES",
        "field_label": "Financial Effects of Climate Risk (IFRS S1/S2)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "IFRS S1 (2023)",
        "legal_basis": "IFRS S1 General Requirements for Disclosure of Sustainability-related Financial Information",
        "penalty_tier": "Medium",
        "enforcement_body": "ISSB / National SDR Jurisdiction",
        "cross_references": [
            {"framework": "SEC", "field_code": "SEC_FINANCIAL_IMPACT", "relationship": "equivalent_disclosure"},
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Financial effects of sustainability-related risks and opportunities in the primary financial statements.",
            "unit": "USD",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_issb_s2_targets",
        "framework": "ISSB",
        "disclosure_type": "entity_pai",
        "annex_code": "IFRS S2 B69",
        "field_code": "ISSB_S2_TARGETS",
        "field_label": "Climate Targets & Progress (IFRS S2)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "IFRS S2 (2023)",
        "legal_basis": "IFRS S2 Climate-related Disclosures, para B69-B71 (targets and progress)",
        "penalty_tier": "Medium",
        "enforcement_body": "ISSB / National SDR Jurisdiction",
        "cross_references": [
            {"framework": "SEC", "field_code": "SEC_GHG_SCOPE1", "relationship": "complementary_indicator"},
            {"framework": "SFDR", "field_code": "PERIODIC_SUSTAIN_INVEST_TARGET", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Quantified climate targets, base year, target year, and progress against each interim milestone.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_issb_s1_materiality",
        "framework": "ISSB",
        "disclosure_type": "entity_pai",
        "annex_code": "IFRS S1",
        "field_code": "ISSB_S1_MATERIALITY",
        "field_label": "Materiality Assessment (IFRS S1)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "IFRS S1 (2023)",
        "legal_basis": "IFRS S1 General Requirements — materiality assessment framework",
        "penalty_tier": "Low",
        "enforcement_body": "ISSB / National SDR Jurisdiction",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "complementary_indicator"},
            {"framework": "SEC", "field_code": "SEC_CLIMATE_RISK", "relationship": "supplementary_data"}
        ],
        "guidance": {
            "description": "Explanation of how the undertaking identifies and prioritises material sustainability-related risks.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    }
]

# =============================================================================
# What-If Scenario Templates
# =============================================================================
WHAT_IF_TEMPLATES = [
    {
        "scenario_name": "Non-disclosure of Scope 3 Emissions",
        "scenario_description": "What if we do NOT disclose Scope 3 GHG emissions this reporting period?",
        "parameters": {
            "action": "remove_field",
            "field_code": "PAI_GHG_SCOPE3",
            "rationale": "Data unavailability from portfolio companies"
        }
    },
    {
        "scenario_name": "Board Gender Diversity Below 30%",
        "scenario_description": "What if our Board Gender Diversity drops below 30%?",
        "parameters": {
            "action": "threshold_change",
            "field_code": "PAI_BOARD_GENDER_DIVERSITY",
            "new_value": 28.5,
            "threshold": 30.0,
            "direction": "below"
        }
    },
    {
        "scenario_name": "Fund Reclassification: Article 8 → Article 6",
        "scenario_description": "What if we reclassify this fund from Article 8 to Article 6?",
        "parameters": {
            "action": "reclassify_article",
            "from_article": "Article 8",
            "to_article": "Article 6",
            "rationale": "Simplified disclosure obligations"
        }
    }
]


def seed_database():
    logger.info("Verifying database seed data...")
    db = SessionLocal()
    try:
        # 1. Seed users representing distinct governance roles
        users_to_seed = [
            {"id": "system", "username": "System Auto-Agent", "email": "system@sfdr.ai", "role": UserRole.ADMINISTRATOR.value},
            {"id": "user_officer", "username": "officer_alice", "email": "alice@greenfield.com", "role": UserRole.COMPLIANCE_OFFICER.value},
            {"id": "user_reviewer", "username": "reviewer_bob", "email": "bob@greenfield.com", "role": UserRole.REVIEWER.value},
            {"id": "user_admin", "username": "admin_charlie", "email": "admin@greenfield.com", "role": UserRole.ADMINISTRATOR.value},
            {"id": "user_auditor", "username": "auditor_dana", "email": "auditor@greenfield.com", "role": UserRole.AUDITOR.value},
            {"id": "user_manan", "username": "manan", "email": "manan@company.com", "role": UserRole.ADMINISTRATOR.value}
        ]
        
        for u in users_to_seed:
            existing = db.query(User).filter(
                (User.id == u["id"]) | (User.username == u["username"])
            ).first()
            if not existing:
                new_user = User(
                    id=u["id"],
                    username=u["username"],
                    email=u["email"],
                    hashed_password=get_password_hash("password123"),
                    role=u["role"],
                    active=True
                )
                db.add(new_user)
                logger.info("Seeded user: %s (%s)", u["username"], u["role"])
        db.commit()

        # 2. Seed default organization if not exists
        org_id = "default_org"
        org = db.query(Organization).filter(Organization.id == org_id).first()
        if not org:
            org = Organization(id=org_id, name="Greenfield Capital Partners Ltd", type="Asset Manager")
            db.add(org)
            db.commit()
            logger.info("Seeded organization: %s", org.name)
        else:
            logger.debug("Organization already exists.")

        # 3. Seed default products if not exists
        prod_id = "default_prod_8"
        prod = db.query(Product).filter(Product.id == prod_id).first()
        if not prod:
            prod = Product(
                id=prod_id,
                organization_id=org_id,
                name="Greenfield Climate Impact Fund (Art 8)",
                sfdr_article="Article 8",
                strategy="Investments in low-carbon energy transition equities and sustainable real estate.",
                benchmark="MSCI World Climate Change Index"
            )
            db.add(prod)
            
            # Also seed an Article 9 product
            prod9 = Product(
                id="default_prod_9",
                organization_id=org_id,
                name="Greenfield Pure Decarbonization Sovereign Fund (Art 9)",
                sfdr_article="Article 9",
                strategy="100% committed to sustainable investments targeting rapid carbon reduction.",
                benchmark="S&P Global Clean Energy Index"
            )
            db.add(prod9)
            
            db.commit()
            logger.info("Seeded default products (Article 8 and Article 9).")
        else:
            logger.debug("Products already exist.")

        # 4. Seed ALL regulation fields (SFDR + CSRD + SEC + UK SDR + ISSB)
        all_fields = SFDR_FIELDS + CSRD_FIELDS + SEC_FIELDS + UK_SDR_FIELDS + ISSB_FIELDS
        seeded_count = 0
        for f in all_fields:
            existing = db.query(RegulationField).filter(RegulationField.field_code == f["field_code"]).first()
            if not existing:
                field = RegulationField(
                    id=f["id"],
                    framework=f["framework"],
                    disclosure_type=f["disclosure_type"],
                    annex_code=f["annex_code"],
                    field_code=f["field_code"],
                    field_label=f["field_label"],
                    field_kind=f["field_kind"],
                    mandatory=f["mandatory"],
                    regulation_version=f["regulation_version"],
                    guidance=f["guidance"],
                    # Legal consequence metadata
                    legal_basis=f.get("legal_basis"),
                    penalty_tier=f.get("penalty_tier", "Medium"),
                    enforcement_body=f.get("enforcement_body"),
                    cross_references=f.get("cross_references")
                )
                db.add(field)
                seeded_count += 1
        
        db.commit()
        logger.info(
            "Seeded %d regulation fields (%d SFDR + %d CSRD + %d SEC + %d UK SDR + %d ISSB).",
            seeded_count, len(SFDR_FIELDS), len(CSRD_FIELDS), len(SEC_FIELDS),
            len(UK_SDR_FIELDS), len(ISSB_FIELDS),
        )
        
    except Exception as e:
        db.rollback()
        logger.error("Error seeding database: %s", e)
        raise e
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()
