import uuid
from app.database import Base, engine, SessionLocal
from app.models import RegulationField, Organization, Product, User, UserRole
from app.auth import get_password_hash

# Seed data for standard SFDR fields
SFDR_FIELDS = [
    # --- Entity-Level PAI (Principal Adverse Impacts) ---
    {
        "id": "field_pai_ghg_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_GHG_SCOPE1",
        "field_label": "Scope 1 GHG Emissions",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "Scope 1 greenhouse gas emissions generated by investee companies.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_ghg_2",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_GHG_SCOPE2",
        "field_label": "Scope 2 GHG Emissions",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "Scope 2 greenhouse gas emissions generated by investee companies.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_ghg_3",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_GHG_SCOPE3",
        "field_label": "Scope 3 GHG Emissions",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "Scope 3 greenhouse gas emissions generated by investee companies.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_carb_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_CARBON_FOOTPRINT",
        "field_label": "Carbon Footprint",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "Carbon footprint of the investment portfolio.",
            "unit": "tCO2e/EURm",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_ff_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_FOSSIL_FUEL",
        "field_label": "Exposure to Fossil Fuel Companies",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "Share of investments in investee companies active in the fossil fuel sector.",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_pai_wat_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_WATER_EMISSIONS",
        "field_label": "Emissions to Water",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "Tonnes of emissions to water generated by investee companies per million EUR invested, expressed as a weighted average.",
            "unit": "tonnes/EURm",
            "rule_checks": ["numeric_only", "must_have_evidence"]
        }
    },
    {
        "id": "field_pai_div_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_BOARD_GENDER_DIVERSITY",
        "field_label": "Board Gender Diversity",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "Average ratio of female to male board members in investee companies.",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    
    # --- Periodic Report Annexes (Article 8 / Article 9) ---
    {
        "id": "field_per_sustain_target",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_SUSTAIN_INVEST_TARGET",
        "field_label": "Attainment of Sustainable Investment Objective",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "To what extent was the sustainable investment objective attained during the reporting period?",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_top_invest",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_TOP_INVESTMENTS",
        "field_label": "Top Investments",
        "field_kind": "table",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "List of top 15 investments of the financial product during the reporting period (Sector, Country, % Assets).",
            "rule_checks": ["table_columns", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_asset_alloc",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_ASSET_ALLOCATION",
        "field_label": "Proportion of Sustainability-related Investments",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "What was the proportion of sustainability-related investments during the reporting period?",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_tax_aligned",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_TAXONOMY_ALIGNMENT",
        "field_label": "Taxonomy-aligned Activities",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "To what extent were the sustainable investments aligned with the EU Taxonomy?",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_social_obj",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_SOCIAL_OBJECTIVE",
        "field_label": "Share of Socially Sustainable Investments",
        "field_kind": "numeric",
        "mandatory": False,
        "regulation_version": "2022/1288",
        "guidance": {
            "description": "What was the share of socially sustainable investments?",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range"]
        }
    }
]

def seed_database():
    print("Database connection...")
    db = SessionLocal()
    try:
        # 1. Seed users representing distinct governance roles
        users_to_seed = [
            {"id": "system", "username": "System Auto-Agent", "email": "system@sfdr.ai", "role": UserRole.ADMINISTRATOR.value},
            {"id": "user_officer", "username": "officer_alice", "email": "alice@greenfield.com", "role": UserRole.COMPLIANCE_OFFICER.value},
            {"id": "user_reviewer", "username": "reviewer_bob", "email": "bob@greenfield.com", "role": UserRole.REVIEWER.value},
            {"id": "user_admin", "username": "admin_charlie", "email": "admin@greenfield.com", "role": UserRole.ADMINISTRATOR.value}
        ]
        
        for u in users_to_seed:
            existing = db.query(User).filter(User.id == u["id"]).first()
            if not existing:
                new_user = User(
                    id=u["id"],
                    username=u["username"],
                    email=u["email"],
                    hashed_password=get_password_hash("password123"),
                    role=u["role"],
                    active=True
                )
                db.add(new_user)
                print(f"Seeded user: {u['username']} ({u['role']})")
        db.commit()

        # 2. Seed default organization if not exists
        org_id = "default_org"
        org = db.query(Organization).filter(Organization.id == org_id).first()
        if not org:
            org = Organization(id=org_id, name="Greenfield Capital Partners Ltd", type="Asset Manager")
            db.add(org)
            db.commit()
            print(f"Seeded organization: {org.name}")
        else:
            print("Organization already exists.")

        # 3. Seed default products if not exists
        prod_id = "default_prod_8"
        prod = db.query(Product).filter(Product.id == prod_id).first()
        if not prod:
            prod = Product(
                id=prod_id,
                organization_id=org_id,
                name="Greenfield Climate Impact Fund (Art 8)",
                sfdr_article="Article 8",
                strategy="Investments in low-carbon energy transition equities and sustainable real estate.",
                benchmark="MSCI World Climate Change Index"
            )
            db.add(prod)
            
            # Also seed an Article 9 product
            prod9 = Product(
                id="default_prod_9",
                organization_id=org_id,
                name="Greenfield Pure Decarbonization Sovereign Fund (Art 9)",
                sfdr_article="Article 9",
                strategy="100% committed to sustainable investments targeting rapid carbon reduction.",
                benchmark="S&P Global Clean Energy Index"
            )
            db.add(prod9)
            
            db.commit()
            print("Seeded default products (Article 8 and Article 9).")
        else:
            print("Products already exist.")

        # 4. Seed regulation fields
        seeded_count = 0
        for f in SFDR_FIELDS:
            existing = db.query(RegulationField).filter(RegulationField.field_code == f["field_code"]).first()
            if not existing:
                field = RegulationField(
                    id=f["id"],
                    framework=f["framework"],
                    disclosure_type=f["disclosure_type"],
                    annex_code=f["annex_code"],
                    field_code=f["field_code"],
                    field_label=f["field_label"],
                    field_kind=f["field_kind"],
                    mandatory=f["mandatory"],
                    regulation_version=f["regulation_version"],
                    guidance=f["guidance"]
                )
                db.add(field)
                seeded_count += 1
        
        db.commit()
        print(f"Seeded {seeded_count} new regulation fields.")
        
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
        raise e
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()
