import React, { useState } from 'react';
import { ArrowLeft, Check, X, Save, FileText, LayoutTemplate } from 'lucide-react';
import { NavLink } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';

const ReviewerDesk = () => {
  const [activeTab, setActiveTab] = useState('narrative');

  return (
    <motion.div 
      initial={{ opacity: 0 }} animate={{ opacity: 1 }}
      className="flex flex-col gap-6 h-full min-h-0 w-full" 
    >
      {/* Top Bar */}
      <div className="glass-card p-6 flex justify-between items-start md:items-center flex-wrap gap-4">
        <div>
          <span className="text-xs font-black text-primary-600 uppercase tracking-wider">Reviewer Workspace</span>
          <h1 className="text-2xl font-bold text-slate-800 mt-1">GHG Scope 1 Emissions</h1>
        </div>
        <NavLink to="/matrix" className="btn btn-secondary border-none shadow-none bg-slate-100/50 hover:bg-slate-200/50 transition-colors">
          <ArrowLeft size={16} />
          <span className="font-semibold">Back to Matrix</span>
        </NavLink>
      </div>

      <div className="flex flex-col lg:flex-row gap-6 flex-1 min-h-0 w-full">
        {/* Left Pane: Evidence */}
        <motion.div 
          initial={{ x: -20, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ delay: 0.1 }}
          className="flex-1 flex flex-col min-h-0" 
        >
          <div className="glass-card p-6 flex flex-col gap-6 h-full overflow-y-auto">
            <div className="flex justify-between items-start gap-4 pb-4 border-b border-slate-100">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-emerald-50 text-emerald-600 flex items-center justify-center">
                  <FileText size={18} />
                </div>
                <h3 className="font-bold text-lg text-slate-800">Supporting Evidence</h3>
              </div>
              <span className="badge badge-success shadow-sm">PAI_GHG_SCOPE1</span>
            </div>
            
            <p className="text-sm font-medium text-slate-500 leading-relaxed">
              Scope 1 greenhouse gas emissions generated by investee companies.
            </p>
            
            <div className="p-6 bg-gradient-to-br from-slate-50 to-white border border-slate-200 rounded-xl flex-1 shadow-inner relative overflow-hidden">
              <div className="absolute top-0 left-0 w-1 h-full bg-primary-500"></div>
              <p className="italic font-medium text-slate-700 text-lg leading-relaxed relative z-10">
                "The total Scope 1 emissions for the reporting year were calculated at 14,230 tCO2e, representing a 5% reduction from the previous baseline."
              </p>
            </div>
            
            <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl text-sm flex flex-col gap-2 mt-auto">
              <div className="flex justify-between">
                <span className="font-semibold text-slate-500">Source Document:</span>
                <span className="text-slate-800 font-medium">2025_Annual_Sustainability_Report.pdf</span>
              </div>
              <div className="flex justify-between">
                <span className="font-semibold text-slate-500">Location:</span>
                <span className="text-slate-800 font-medium">Page 24</span>
              </div>
              <div className="flex justify-between items-center mt-2 pt-2 border-t border-slate-200">
                <span className="font-bold text-slate-700">Extraction Confidence:</span>
                <span className="text-emerald-600 font-black text-base flex items-center gap-1">
                  <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></div>
                  98%
                </span>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Right Pane: Draft Editor */}
        <motion.div 
          initial={{ x: 20, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ delay: 0.2 }}
          className="flex-1 flex flex-col min-h-0" 
        >
          <div className="glass-card p-6 flex flex-col gap-6 h-full overflow-y-auto">
            <div className="flex justify-between items-start gap-4 pb-4 border-b border-slate-100">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-primary-50 text-primary-600 flex items-center justify-center">
                  <LayoutTemplate size={18} />
                </div>
                <h3 className="font-bold text-lg text-slate-800">Disclosure Drafting</h3>
              </div>
              <span className="badge badge-default shadow-sm">Draft Phase</span>
            </div>

            {/* Tabs */}
            <div className="flex gap-2 p-1 bg-slate-100 rounded-lg relative overflow-hidden shrink-0">
              <button 
                className={`flex-1 py-2 px-4 font-semibold text-sm rounded-md transition-all z-10 ${activeTab === 'narrative' ? 'text-primary-700 shadow-sm bg-white' : 'text-slate-500 hover:text-slate-700 hover:bg-slate-200/50'}`}
                onClick={() => setActiveTab('narrative')}
              >
                Narrative Draft
              </button>
              <button 
                className={`flex-1 py-2 px-4 font-semibold text-sm rounded-md transition-all z-10 ${activeTab === 'json' ? 'text-primary-700 shadow-sm bg-white' : 'text-slate-500 hover:text-slate-700 hover:bg-slate-200/50'}`}
                onClick={() => setActiveTab('json')}
              >
                Structured Values
              </button>
            </div>

            <div className="flex-1 min-h-[250px] relative mt-2">
              <AnimatePresence mode="wait">
                {activeTab === 'narrative' ? (
                  <motion.div 
                    key="narrative"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    className="absolute inset-0 flex flex-col"
                  >
                    <label className="form-label">Draft Narrative Statement</label>
                    <textarea 
                      className="form-input flex-1 resize-none bg-white focus:bg-white shadow-sm font-medium text-slate-700 leading-relaxed p-4" 
                      defaultValue="The total Scope 1 emissions for the reporting year were calculated at 14,230 tCO2e."
                    ></textarea>
                  </motion.div>
                ) : (
                  <motion.div 
                    key="json"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    className="absolute inset-0 flex flex-col"
                  >
                    <label className="form-label">Interactive Structured Data Grid</label>
                    <div className="flex gap-4 mt-2 flex-wrap">
                      <div className="flex-1 min-w-[150px]">
                        <label className="block text-xs font-bold text-slate-500 mb-1 uppercase tracking-wider">Extracted Numeric Value</label>
                        <input type="number" className="form-input shadow-sm font-mono text-lg font-bold text-slate-800" defaultValue={14230} />
                      </div>
                      <div className="flex-1 min-w-[150px]">
                        <label className="block text-xs font-bold text-slate-500 mb-1 uppercase tracking-wider">Reporting Unit</label>
                        <input type="text" className="form-input shadow-sm font-mono text-lg font-bold text-slate-800" defaultValue="tCO2e" />
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Validation & Actions */}
            <div className="mt-auto pt-6 border-t border-slate-100 flex flex-col gap-5 shrink-0">
              <div className="bg-emerald-50 border border-emerald-100 rounded-xl p-3 flex items-center justify-center gap-2">
                <div className="w-5 h-5 rounded-full bg-emerald-500 text-white flex items-center justify-center">
                  <Check size={12} strokeWidth={3} />
                </div>
                <span className="font-bold text-emerald-800 text-sm">Automated Validation: 100% Compliant</span>
              </div>
              <div className="flex flex-wrap gap-3">
                <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} className="btn bg-slate-100 text-slate-700 hover:bg-slate-200 border-none flex-1 font-bold shadow-sm">
                  <Save size={16} /> Save Draft
                </motion.button>
                <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} className="btn btn-primary flex-1 font-bold">
                  <Check size={16} /> Approve
                </motion.button>
                <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} className="btn bg-rose-50 text-rose-600 hover:bg-rose-100 border-none flex-1 font-bold shadow-sm">
                  <X size={16} /> Reject
                </motion.button>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </motion.div>
  );
};

export default ReviewerDesk;
